apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jacky-rolebinding
  namespace: deep-ns
subjects:
- kind: User
  name: jacky
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: jacky-custom-role-ro
  apiGroup: rbac.authorization.k8s.io
